import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  iconButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    border: 'none',
    color: 'white',
    fontSize: '10px',
    fontWeight: 'bold',
    cursor: 'pointer',
    marginLeft: '4px',
    verticalAlign: 'middle',
    lineHeight: 1,
    padding: 0,
  },
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 999999,
  },
  modal: {
    backgroundColor: 'white',
    borderRadius: '12px',
    maxWidth: '500px',
    width: '90%',
    maxHeight: '80vh',
    overflow: 'auto',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
    cursor: 'default',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    borderBottom: '1px solid #e5e7eb',
    position: 'sticky',
    top: 0,
    backgroundColor: 'white',
  },
  title: {
    margin: 0,
    fontSize: '18px',
    fontWeight: 600,
    color: '#1f2937',
  },
  closeButton: {
    background: 'none',
    border: 'none',
    fontSize: '24px',
    cursor: 'pointer',
    color: '#6b7280',
    padding: '0 4px',
  },
  content: {
    padding: '20px',
  },
  section: {
    marginBottom: '20px',
  },
  sectionTitle: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#374151',
    marginTop: 0,
    marginBottom: '8px',
  },
  badge: {
    display: 'inline-block',
    padding: '4px 12px',
    borderRadius: '9999px',
    color: 'white',
    fontSize: '12px',
    fontWeight: 600,
    marginBottom: '8px',
  },
  reason: {
    fontSize: '14px',
    color: '#4b5563',
    lineHeight: 1.5,
    margin: '8px 0',
    whiteSpace: 'normal',
  },
  meta: {
    fontSize: '12px',
    color: '#9ca3af',
    margin: '4px 0 0 0',
  },
  rosterCard: {
    backgroundColor: '#f9fafb',
    borderRadius: '8px',
    padding: '12px',
    marginBottom: '12px',
    whiteSpace: 'normal',
  },
  rosterHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  upgradeCard: {
    backgroundColor: '#f9fafb',
    borderRadius: '8px',
    padding: '12px',
    marginBottom: '12px',
    whiteSpace: 'normal',
  },
  upgradeHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '8px',
  },
  addBadge: {
    backgroundColor: '#22c55e',
    color: 'white',
    padding: '4px 12px',
    borderRadius: '9999px',
    fontSize: '12px',
    fontWeight: 600,
    marginBottom: '8px',
  },
  playerName: {
    fontWeight: 600,
    color: '#1f2937',
  },
  strengthContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '8px',
  },
  strengthDots: {
    display: 'flex',
    gap: '4px',
  },
  strengthDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
  },
  strengthLabel: {
    fontSize: '13px',
    fontWeight: 600,
  },
  noRecs: {
    color: '#6b7280',
    fontStyle: 'italic',
  },
  injuryNote: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '8px',
    backgroundColor: '#fef3c7',
    border: '1px solid #f59e0b',
    borderRadius: '6px',
    padding: '8px 12px',
    marginTop: '8px',
    marginBottom: '8px',
    fontSize: '13px',
    color: '#92400e',
    lineHeight: 1.4,
    whiteSpace: 'normal',
  },
  injuryIcon: {
    flexShrink: 0,
    fontSize: '14px',
  },
  titlePlayerLink: {
    color: '#7c3aed',
    textDecoration: 'none',
  },
  playerLink: {
    color: '#7c3aed',
    fontWeight: 600,
    textDecoration: 'none',
  },
};

export const bannerStyles: Record<string, React.CSSProperties> = {
  container: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#7c3aed',
    color: 'white',
    zIndex: 999998,
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.15)',
  },
  content: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '12px 20px',
    maxWidth: '1200px',
    margin: '0 auto',
    gap: '16px',
  },
  spinnerContainer: {
    flexShrink: 0,
  },
  spinner: {
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    border: '2px solid rgba(255, 255, 255, 0.3)',
    borderTopColor: 'white',
    animation: 'fantasy-edge-spin 1s linear infinite',
  },
  textContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  title: {
    fontWeight: 600,
    fontSize: '14px',
  },
  step: {
    fontSize: '12px',
    opacity: 0.9,
  },
  progressContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
  },
  progressBar: {
    width: '100px',
    height: '6px',
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: '3px',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: 'white',
    borderRadius: '3px',
    transition: 'width 0.3s ease',
  },
  progressText: {
    fontSize: '12px',
    fontWeight: 600,
    minWidth: '35px',
  },
  successIcon: {
    fontSize: '18px',
    fontWeight: 'bold',
  },
  successText: {
    fontSize: '14px',
  },
  rosterLink: {
    color: 'white',
    textDecoration: 'underline',
    fontWeight: 600,
  },
  errorIcon: {
    fontSize: '18px',
  },
  errorText: {
    fontSize: '14px',
  },
  dismissButton: {
    background: 'none',
    border: 'none',
    color: 'white',
    fontSize: '20px',
    cursor: 'pointer',
    padding: '0 4px',
    opacity: 0.8,
    marginLeft: 'auto',
  },
};

